import { env } from "../../config/env.js";
import type { AiRevenueSettings } from "../../types/ai-revenue-agent.js";
import { formatDateKeyInTimeZone, formatTimeKeyInTimeZone, normalizeTimeZone } from "../telegram/time.js";
import { listAgentLearningSchedules } from "../agent-hub/learning.repository.js";
import { generateAiRevenueActions } from "./ai-revenue-agent.service.js";
import * as repository from "./ai-revenue-agent.repository.js";

export const AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB = "ai_revenue_generate_today_opportunities" as const;

export type AiRevenueScheduledGenerationSummary = repository.AiRevenueBatchRunSummary & {
  jobName: typeof AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB;
  dateKey: string;
  timezone: string;
  dueClinics: number;
  dryRun: boolean;
};

type ClinicGenerationTarget = AiRevenueSettings & {
  resolvedClinicCode: string | null;
};

function minutesSinceMidnight(timeKey: string) {
  const [hour, minute] = timeKey.split(":").map(Number);
  if (!Number.isFinite(hour) || !Number.isFinite(minute)) {
    return null;
  }

  return hour * 60 + minute;
}

function isWithinRunWindow(timeKey: string, targetTimeKey: string, windowMinutes = 15) {
  const current = minutesSinceMidnight(timeKey);
  const target = minutesSinceMidnight(targetTimeKey);

  if (current == null || target == null) {
    return false;
  }

  return current >= target && current < target + windowMinutes;
}

export function isAiRevenueAutoGenerateDue(params: {
  settings: Pick<AiRevenueSettings, "timezone" | "dailyGenerateTime">;
  now: Date;
}) {
  const timezone = normalizeTimeZone(params.settings.timezone || env.DEFAULT_TIMEZONE);
  const localTime = formatTimeKeyInTimeZone(params.now, timezone);
  return isWithinRunWindow(localTime, params.settings.dailyGenerateTime || "06:00");
}

function emptySummary(params: {
  dateKey: string;
  timezone: string;
  totalClinics: number;
  dueClinics: number;
  dryRun: boolean;
  skippedReason?: string | null;
}): AiRevenueScheduledGenerationSummary {
  return {
    jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
    dateKey: params.dateKey,
    timezone: params.timezone,
    dueClinics: params.dueClinics,
    dryRun: params.dryRun,
    skippedReason: params.skippedReason ?? null,
    totalClinics: params.totalClinics,
    processedClinics: 0,
    skippedClinics: 0,
    failedClinics: 0,
    totalCreated: 0,
    totalDuplicateSkipped: 0,
    totalSuppressedSkipped: 0,
  };
}

async function writeAudit(input: {
  clinicId: string;
  action: string;
  description: string;
  afterValue?: unknown;
}) {
  await repository.createAuditLog({
    clinicId: input.clinicId,
    actionId: null,
    actorType: "system",
    actorId: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
    action: input.action,
    description: input.description,
    afterValue: input.afterValue,
  });
}

function zeroDueReason(params: {
  totalAutoEnabledClinics: number;
  dueClinics: number;
  forcedDateKey: boolean;
}) {
  if (params.dueClinics > 0) {
    return null;
  }

  if (params.totalAutoEnabledClinics === 0) {
    return "no enabled settings";
  }

  if (params.forcedDateKey) {
    return "forced date run has no due clinics";
  }

  return "not in dailyGenerateTime window";
}

function logScheduledGeneration(event: string, payload: Record<string, unknown>) {
  console.info(`[ai-revenue-scheduler] ${event}`, payload);
}

async function resolveClinicCodes(settings: AiRevenueSettings[]): Promise<ClinicGenerationTarget[]> {
  if (settings.length === 0) {
    return [];
  }

  const clinicIds = settings.map((item) => item.clinicId);
  let clinicCodeById = new Map<string, string>();

  try {
    const schedules = await listAgentLearningSchedules({ clinicIds, limit: Math.max(1, clinicIds.length) });
    clinicCodeById = new Map(schedules.map((schedule) => [schedule.clinicId, schedule.clinicCode]));
  } catch {
    clinicCodeById = new Map();
  }

  return settings.map((item) => ({
    ...item,
    resolvedClinicCode: item.clinicCode?.trim() || clinicCodeById.get(item.clinicId) || null,
  }));
}

export async function runScheduledAiRevenueGeneration(params?: {
  now?: Date;
  dateKey?: string;
  timezone?: string;
  dryRun?: boolean;
}): Promise<AiRevenueScheduledGenerationSummary> {
  const now = params?.now ?? new Date();
  const timezone = normalizeTimeZone(params?.timezone || env.DEFAULT_TIMEZONE);
  const batchDateKey = params?.dateKey ?? formatDateKeyInTimeZone(now, timezone);
  const startedAt = new Date().toISOString();
  const allSettings = await repository.listAutoGenerateEnabledSettings();
  const dueSettings = params?.dateKey
    ? allSettings
    : allSettings.filter((settings) => isAiRevenueAutoGenerateDue({ settings, now }));
  const targets = await resolveClinicCodes(dueSettings);
  const skippedReason = zeroDueReason({
    totalAutoEnabledClinics: allSettings.length,
    dueClinics: targets.length,
    forcedDateKey: Boolean(params?.dateKey),
  });
  const summary = emptySummary({
    dateKey: batchDateKey,
    timezone,
    totalClinics: allSettings.length,
    dueClinics: targets.length,
    dryRun: Boolean(params?.dryRun),
    skippedReason,
  });

  if (params?.dryRun) {
    summary.skippedClinics = targets.length;
    logScheduledGeneration("dry_run", summary);
    return summary;
  }

  logScheduledGeneration("batch_started", {
    dateKey: batchDateKey,
    timezone,
    totalAutoEnabledClinics: summary.totalClinics,
    dueClinics: summary.dueClinics,
    skippedReason,
  });
  await repository.saveAiRevenueBatchRun({
    jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
    dateKey: batchDateKey,
    timezone,
    status: "running",
    startedAt,
    summary,
  });
  await writeAudit({
    clinicId: "ai_revenue_batch",
    action: "scheduled_generation_batch_started",
    description: "Started scheduled AI Revenue opportunity generation batch.",
    afterValue: {
      dateKey: batchDateKey,
      totalClinics: summary.totalClinics,
      dueClinics: summary.dueClinics,
      skippedReason,
    },
  });

  for (const target of targets) {
    const clinicTimezone = normalizeTimeZone(target.timezone || timezone);
    const clinicDateKey = params?.dateKey ?? formatDateKeyInTimeZone(now, clinicTimezone);
    const lock = await repository.acquireAiRevenueClinicRunLock({
      jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
      clinicId: target.clinicId,
      clinicCode: target.resolvedClinicCode,
      clinicName: target.clinicName,
      dateKey: clinicDateKey,
      timezone: clinicTimezone,
    });

    if (!lock.acquired) {
      summary.skippedClinics += 1;
      logScheduledGeneration("clinic_skipped", {
        clinicId: target.clinicId,
        clinicName: target.clinicName,
        dateKey: clinicDateKey,
        reason: lock.reason,
      });
      await writeAudit({
        clinicId: target.clinicId,
        action: "scheduled_generation_clinic_skipped",
        description:
          lock.reason === "completed"
            ? "Skipped scheduled AI Revenue generation because this clinic/date is already completed."
            : "Skipped scheduled AI Revenue generation because another run still holds the clinic/date lock.",
        afterValue: {
          dateKey: clinicDateKey,
          reason: lock.reason,
        },
      });
      continue;
    }

    await writeAudit({
      clinicId: target.clinicId,
      action: "scheduled_generation_clinic_started",
      description: "Started scheduled AI Revenue opportunity generation for this clinic.",
      afterValue: {
        dateKey: clinicDateKey,
        clinicName: target.clinicName,
      },
    });

    if (!target.resolvedClinicCode) {
      const error = new Error("clinicCode is required for scheduled AI Revenue opportunity generation.");
      summary.failedClinics += 1;
      logScheduledGeneration("clinic_failed", {
        clinicId: target.clinicId,
        clinicName: target.clinicName,
        dateKey: clinicDateKey,
        error: error.message,
      });
      await repository.completeAiRevenueClinicRun({
        jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
        clinicId: target.clinicId,
        clinicCode: null,
        clinicName: target.clinicName,
        dateKey: clinicDateKey,
        timezone: clinicTimezone,
        status: "failed",
        error,
      });
      await repository.updateSettingsAutoGenerationStatus({
        clinicId: target.clinicId,
        status: "failed",
        generatedAt: new Date().toISOString(),
      });
      await writeAudit({
        clinicId: target.clinicId,
        action: "scheduled_generation_error",
        description: error.message,
        afterValue: {
          dateKey: clinicDateKey,
        },
      });
      continue;
    }

    try {
      const result = await generateAiRevenueActions({
        clinicId: target.clinicId,
        clinicCode: target.resolvedClinicCode,
        dateKey: clinicDateKey,
        forceRefresh: false,
      });
      const createdCount = result.generatedCount;
      const duplicateSkippedCount = result.skippedExistingCount;
      const suppressedSkippedCount = result.suppressedSkippedCount;

      summary.processedClinics += 1;
      summary.totalCreated += createdCount;
      summary.totalDuplicateSkipped += duplicateSkippedCount;
      summary.totalSuppressedSkipped += suppressedSkippedCount;

      await repository.completeAiRevenueClinicRun({
        jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
        clinicId: target.clinicId,
        clinicCode: target.resolvedClinicCode,
        clinicName: target.clinicName,
        dateKey: clinicDateKey,
        timezone: clinicTimezone,
        status: "completed",
        createdCount,
        duplicateSkippedCount,
        suppressedSkippedCount,
      });
      await repository.updateSettingsAutoGenerationStatus({
        clinicId: target.clinicId,
        status: "completed",
        generatedAt: new Date().toISOString(),
      });
      logScheduledGeneration("clinic_completed", {
        clinicId: target.clinicId,
        clinicName: target.clinicName,
        dateKey: clinicDateKey,
        createdCount,
        duplicateSkippedCount,
        suppressedSkippedCount,
        refreshedExistingCount: result.refreshedExistingCount,
      });

      if (duplicateSkippedCount > 0) {
        await writeAudit({
          clinicId: target.clinicId,
          action: "scheduled_generation_duplicates_skipped",
          description: "Skipped existing AI Revenue opportunities during scheduled generation.",
          afterValue: {
            dateKey: clinicDateKey,
            duplicateSkippedCount,
          },
        });
      }

      if (suppressedSkippedCount > 0) {
        await writeAudit({
          clinicId: target.clinicId,
          action: "scheduled_generation_suppressions_skipped",
          description: "Skipped suppressed customers during scheduled AI Revenue generation.",
          afterValue: {
            dateKey: clinicDateKey,
            suppressedSkippedCount,
          },
        });
      }

      await writeAudit({
        clinicId: target.clinicId,
        action: "scheduled_generation_clinic_completed",
        description: "Completed scheduled AI Revenue opportunity generation for this clinic.",
        afterValue: {
          dateKey: clinicDateKey,
          createdCount,
          duplicateSkippedCount,
          suppressedSkippedCount,
          refreshedExistingCount: result.refreshedExistingCount,
        },
      });
    } catch (error) {
      summary.failedClinics += 1;
      logScheduledGeneration("clinic_failed", {
        clinicId: target.clinicId,
        clinicName: target.clinicName,
        dateKey: clinicDateKey,
        error: error instanceof Error ? error.message : "Scheduled AI Revenue generation failed.",
      });
      await repository.completeAiRevenueClinicRun({
        jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
        clinicId: target.clinicId,
        clinicCode: target.resolvedClinicCode,
        clinicName: target.clinicName,
        dateKey: clinicDateKey,
        timezone: clinicTimezone,
        status: "failed",
        error,
      });
      await repository.updateSettingsAutoGenerationStatus({
        clinicId: target.clinicId,
        status: "failed",
        generatedAt: new Date().toISOString(),
      });
      await writeAudit({
        clinicId: target.clinicId,
        action: "scheduled_generation_error",
        description: error instanceof Error ? error.message : "Scheduled AI Revenue generation failed.",
        afterValue: {
          dateKey: clinicDateKey,
        },
      });
    }
  }

  await repository.saveAiRevenueBatchRun({
    jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
    dateKey: batchDateKey,
    timezone,
    status: summary.failedClinics > 0 ? "failed" : "completed",
    startedAt,
    completedAt: new Date().toISOString(),
    summary,
  });
  await writeAudit({
    clinicId: "ai_revenue_batch",
    action: "scheduled_generation_batch_completed",
    description: "Completed scheduled AI Revenue opportunity generation batch.",
    afterValue: summary,
  });
  logScheduledGeneration("batch_completed", summary);

  return summary;
}

export async function getScheduledAiRevenueClinicRun(params: {
  clinicId: string;
  dateKey: string;
}) {
  return repository.getAiRevenueClinicRun({
    jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
    clinicId: params.clinicId,
    dateKey: params.dateKey,
  });
}
