import assert from "node:assert/strict";
import test from "node:test";

process.env.APICORE_GRAPHQL_URL ??= "https://example.com/graphql";
process.env.AGENT_LEARNING_ENABLED = "true";

const { agentLearningTickSchema } = await import("../src/services/agent-hub/schemas.ts");
const {
  AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
  isAiRevenueAutoGenerateDue,
  resolveAiRevenueClinicCodes,
} = await import("../src/services/ai-revenue-agent/scheduled-generation.service.ts");
const { env } = await import("../src/config/env.ts");
const {
  runAgentLearningForSchedules,
  shouldRunAiRevenueGenerationForScheduledJobs,
} = await import("../src/services/agent-hub/learning-worker.ts");
const { buildAiRevenueSettingsPatch } = await import("../src/routes/ai-revenue-agent.routes.ts");
const { scheduledAiRevenueGenerationHttpStatus } = await import("../src/routes/telegram.routes.ts");
const { shouldUseAiRevenueRunSummary } = await import(
  "../src/services/ai-revenue-agent/ai-revenue-agent.service.ts"
);

function buildScheduledSummary(overrides: Record<string, unknown> = {}) {
  return {
    jobName: AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
    dateKey: "2026-07-07",
    timezone: "Asia/Yangon",
    dueClinics: 0,
    dryRun: false,
    totalClinics: 0,
    processedClinics: 0,
    skippedClinics: 0,
    failedClinics: 0,
    totalCreated: 0,
    totalDuplicateSkipped: 0,
    totalSuppressedSkipped: 0,
    ...overrides,
  };
}

test("AI Revenue scheduled generation catches up after the 06:00 Yangon time", () => {
  const settings = {
    timezone: "Asia/Yangon",
    dailyGenerateTime: "06:00",
    lastAutoGeneratedAt: null,
    lastAutoGenerateStatus: null,
  };

  assert.equal(
    isAiRevenueAutoGenerateDue({
      settings,
      now: new Date("2026-07-06T23:30:00.000Z"),
    }),
    true,
  );
  assert.equal(
    isAiRevenueAutoGenerateDue({
      settings,
      now: new Date("2026-07-06T23:45:00.000Z"),
    }),
    true,
  );
  assert.equal(
    isAiRevenueAutoGenerateDue({
      settings: {
        ...settings,
        lastAutoGeneratedAt: "2026-07-06T23:30:00.000Z",
        lastAutoGenerateStatus: "completed",
      },
      now: new Date("2026-07-06T23:45:00.000Z"),
    }),
    false,
  );
});

test("AI Revenue clinic-code resolution retries APICORE and persists a recovered code", async () => {
  let lookupAttempts = 0;
  const retryDelays: number[] = [];
  const persisted: Array<{ clinicId: string; resolvedClinicCode: string | null }> = [];
  const settings = {
    clinicId: "clinic-1",
    clinicCode: null,
    clinicName: "The Queen",
    aiRevenueAgentEnabled: true,
    autoGenerateTodayOpportunities: true,
    timezone: "Asia/Yangon",
    dailyGenerateTime: "06:00",
    runOrder: 0,
    language: "my-MM" as const,
    messagingMode: "manual" as const,
    approvalRequired: true,
    attributionWindowDays: 30,
    maxActionsPerRun: 100,
    lastAutoGeneratedAt: null,
    lastAutoGenerateStatus: null,
    updatedAt: null,
    updatedBy: null,
  };

  const targets = await resolveAiRevenueClinicCodes([settings], {}, {
    listSchedules: async () => [],
    lookupClinicCodes: async () => {
      lookupAttempts += 1;
      if (lookupAttempts < 3) {
        throw new Error("APICORE timeout");
      }
      return { "clinic-1": "GTTHEQUEEN" };
    },
    wait: async (milliseconds) => {
      retryDelays.push(milliseconds);
    },
    persistResolvedCode: async (target) => {
      persisted.push({
        clinicId: target.clinicId,
        resolvedClinicCode: target.resolvedClinicCode,
      });
    },
  });

  assert.equal(lookupAttempts, 3);
  assert.deepEqual(retryDelays, [500, 1_000]);
  assert.equal(targets[0]?.resolvedClinicCode, "GTTHEQUEEN");
  assert.deepEqual(persisted, [{ clinicId: "clinic-1", resolvedClinicCode: "GTTHEQUEEN" }]);
});

test("AI Revenue clinic-code resolution uses a stored code without calling APICORE", async () => {
  let lookupAttempts = 0;
  const settings = {
    clinicId: "clinic-1",
    clinicCode: " GTTHEQUEEN ",
    clinicName: "The Queen",
    aiRevenueAgentEnabled: true,
    autoGenerateTodayOpportunities: true,
    timezone: "Asia/Yangon",
    dailyGenerateTime: "06:00",
    runOrder: 0,
    language: "my-MM" as const,
    messagingMode: "manual" as const,
    approvalRequired: true,
    attributionWindowDays: 30,
    maxActionsPerRun: 100,
    lastAutoGeneratedAt: null,
    lastAutoGenerateStatus: null,
    updatedAt: null,
    updatedBy: null,
  };

  const targets = await resolveAiRevenueClinicCodes([settings], {}, {
    listSchedules: async () => [],
    lookupClinicCodes: async () => {
      lookupAttempts += 1;
      return {};
    },
    persistResolvedCode: async () => undefined,
  });

  assert.equal(lookupAttempts, 0);
  assert.equal(targets[0]?.resolvedClinicCode, "GTTHEQUEEN");
});

test("AI Revenue scheduler returns a retryable HTTP status when any clinic fails", () => {
  assert.equal(scheduledAiRevenueGenerationHttpStatus({ failedClinics: 0 }), 200);
  assert.equal(scheduledAiRevenueGenerationHttpStatus({ failedClinics: 1 }), 503);
});

test("AI Revenue status keeps completed run metrics written before the clinic lock completes", () => {
  assert.equal(
    shouldUseAiRevenueRunSummary({
      clinicRun: {
        status: "completed",
        startedAt: "2026-07-23T01:00:00.000Z",
        completedAt: "2026-07-23T01:01:01.000Z",
      },
      runSummary: {
        updatedAt: "2026-07-23T01:01:00.000Z",
      },
    }),
    true,
  );
});

test("AI Revenue status does not hide a newer running or failed attempt behind an old summary", () => {
  assert.equal(
    shouldUseAiRevenueRunSummary({
      clinicRun: {
        status: "running",
        startedAt: "2026-07-23T02:00:00.000Z",
        completedAt: null,
      },
      runSummary: {
        updatedAt: "2026-07-23T01:01:00.000Z",
      },
    }),
    false,
  );
  assert.equal(
    shouldUseAiRevenueRunSummary({
      clinicRun: {
        status: "failed",
        startedAt: "2026-07-23T02:00:00.000Z",
        completedAt: "2026-07-23T02:01:00.000Z",
      },
      runSummary: {
        updatedAt: "2026-07-23T01:01:00.000Z",
      },
    }),
    false,
  );
});

test("AI Revenue scheduled generation runs when Agent Learning is disabled", async () => {
  const previousValue = env.AGENT_LEARNING_ENABLED;
  env.AGENT_LEARNING_ENABLED = false;

  try {
    const calls: unknown[] = [];
    const result = await runAgentLearningForSchedules(
      { now: new Date("2026-07-06T23:30:00.000Z") },
      {
        listSchedules: async () => {
          throw new Error("Agent Learning schedules should not be read when Agent Learning is disabled.");
        },
        runAiRevenueGeneration: async (params) => {
          calls.push(params);
          return buildScheduledSummary({ dueClinics: 1, totalClinics: 1, processedClinics: 1, totalCreated: 2 });
        },
      },
    );

    assert.equal(result.enabled, true);
    assert.equal(calls.length, 1);
    assert.equal(result.aiRevenue?.totalCreated, 2);
  } finally {
    env.AGENT_LEARNING_ENABLED = previousValue;
  }
});

test("agent learning tick schema accepts the AI Revenue generation job", () => {
  const parsed = agentLearningTickSchema.parse({
    jobTypes: [AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB],
    runAt: "2026-07-06T23:30:00.000Z",
  });

  assert.deepEqual(parsed.jobTypes, [AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB]);
});

test("runAgentLearningForSchedules includes AI Revenue generation when jobTypes are omitted", async () => {
  const calls: unknown[] = [];
  const result = await runAgentLearningForSchedules(
    { now: new Date("2026-07-06T23:30:00.000Z") },
    {
      listSchedules: async () => [],
      runAiRevenueGeneration: async (params) => {
        calls.push(params);
        return buildScheduledSummary({ dueClinics: 1, totalClinics: 1, processedClinics: 1, totalCreated: 3 });
      },
    },
  );

  assert.equal(shouldRunAiRevenueGenerationForScheduledJobs(), true);
  assert.equal(calls.length, 1);
  assert.equal(result.aiRevenue?.jobName, AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB);
  assert.equal(result.totalCreated, 3);
});

test("runAgentLearningForSchedules respects explicit jobTypes that exclude AI Revenue", async () => {
  const calls: unknown[] = [];
  const result = await runAgentLearningForSchedules(
    {
      jobTypes: ["customer_profiles"],
      now: new Date("2026-07-06T23:30:00.000Z"),
    },
    {
      listSchedules: async () => [],
      runAiRevenueGeneration: async (params) => {
        calls.push(params);
        return buildScheduledSummary();
      },
    },
  );

  assert.equal(shouldRunAiRevenueGenerationForScheduledJobs(["customer_profiles"]), false);
  assert.equal(calls.length, 0);
  assert.equal(result.aiRevenue, null);
});

test("runAgentLearningForSchedules runs AI Revenue when explicit jobTypes include it", async () => {
  const calls: unknown[] = [];
  const result = await runAgentLearningForSchedules(
    {
      jobTypes: [AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB],
      now: new Date("2026-07-06T23:30:00.000Z"),
      dryRun: true,
    },
    {
      listSchedules: async () => [],
      runAiRevenueGeneration: async (params) => {
        calls.push(params);
        return buildScheduledSummary({ dryRun: true, skippedClinics: 1 });
      },
    },
  );

  assert.equal(shouldRunAiRevenueGenerationForScheduledJobs([AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB]), true);
  assert.equal(calls.length, 1);
  assert.deepEqual(calls[0], {
    now: new Date("2026-07-06T23:30:00.000Z"),
    dryRun: true,
  });
  assert.equal(result.aiRevenue?.dryRun, true);
});

test("AI Revenue settings route patch includes automatic generation settings", () => {
  const patch = buildAiRevenueSettingsPatch({
    clinicId: "clinic-1",
    clinicCode: "GT001",
    clinicName: "Great Time Yangon",
    aiRevenueAgentEnabled: true,
    autoGenerateTodayOpportunities: true,
    timezone: "Asia/Yangon",
    dailyGenerateTime: "06:15",
    runOrder: 7,
    language: "my-MM",
    messagingMode: "manual",
    approvalRequired: true,
    attributionWindowDays: 45,
    maxActionsPerRun: 80,
  });

  assert.deepEqual(patch, {
    clinicCode: "GT001",
    clinicName: "Great Time Yangon",
    aiRevenueAgentEnabled: true,
    autoGenerateTodayOpportunities: true,
    timezone: "Asia/Yangon",
    dailyGenerateTime: "06:15",
    runOrder: 7,
    language: "my-MM",
    messagingMode: "manual",
    approvalRequired: true,
    attributionWindowDays: 45,
    maxActionsPerRun: 80,
  });
});

test("AI Revenue settings route patch omits undefined fields so partial saves do not reset settings", () => {
  const patch = buildAiRevenueSettingsPatch({
    clinicId: "clinic-1",
    aiRevenueAgentEnabled: true,
  });

  assert.deepEqual(patch, {
    aiRevenueAgentEnabled: true,
  });
});
