import assert from "node:assert/strict";
import test from "node:test";

process.env.APICORE_GRAPHQL_URL ??= "https://example.com/graphql";

const { agentLearningTickSchema } = await import("../src/services/agent-hub/schemas.ts");
const {
  AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB,
  isAiRevenueAutoGenerateDue,
} = await import("../src/services/ai-revenue-agent/scheduled-generation.service.ts");

test("AI Revenue scheduled generation is due in the 06:00 Yangon tick window", () => {
  const settings = {
    timezone: "Asia/Yangon",
    dailyGenerateTime: "06:00",
  };

  assert.equal(
    isAiRevenueAutoGenerateDue({
      settings,
      now: new Date("2026-07-06T23:30:00.000Z"),
    }),
    true,
  );
  assert.equal(
    isAiRevenueAutoGenerateDue({
      settings,
      now: new Date("2026-07-06T23:44:59.000Z"),
    }),
    true,
  );
  assert.equal(
    isAiRevenueAutoGenerateDue({
      settings,
      now: new Date("2026-07-06T23:45:00.000Z"),
    }),
    false,
  );
});

test("agent learning tick schema accepts the AI Revenue generation job", () => {
  const parsed = agentLearningTickSchema.parse({
    jobTypes: [AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB],
    runAt: "2026-07-06T23:30:00.000Z",
  });

  assert.deepEqual(parsed.jobTypes, [AI_REVENUE_GENERATE_TODAY_OPPORTUNITIES_JOB]);
});
